import type { StoreListing } from "../../lib/types";

/**
 * Mock community agents used as a design preview in the Store page.
 * These are NOT installable. The detail dialog shows a "Preview, not yet
 * available" notice and the install button stays disabled.
 *
 * When the real community marketplace ships, this file disappears and the
 * Store page reads everything from the engine catalog.
 */
export const MOCK_COMMUNITY_AGENTS: StoreListing[] = [
  {
    id: "mock-recruiter-pro",
    name: "Recruiter Pro",
    description:
      "Source candidates from LinkedIn, score resumes, schedule first-round screens. Drafts personalized outreach but never sends without your review.",
    category: "people",
    author: "Lisa Martinez",
    tags: ["recruiting", "hiring", "linkedin", "sourcing"],
    icon_url: "users",
    integrations: ["linkedin", "gmail", "googlecalendar", "notion"],
    repo: "lmartinez/recruiter-pro",
    installs: 234,
    registered_at: "2026-03-12",
    version: "0.8.1",
    source: "community",
    verified: false,
    rating: 4.7,
    reviews_count: 41,
    stars: 312,
    publisher: {
      name: "Lisa Martinez",
      handle: "lmartinez",
      github_url: "https://github.com/lmartinez",
      verified: false,
    },
    pricing: { kind: "free" },
  },
  {
    id: "mock-content-studio",
    name: "Content Studio",
    description:
      "Plan a month of social content, write captions in your voice, schedule drafts to Buffer. Audits performance weekly and proposes next experiments.",
    category: "marketing",
    author: "marketdev",
    tags: ["content", "social", "buffer", "scheduling"],
    icon_url: "megaphone",
    integrations: ["buffer", "instagram", "linkedin", "twitter", "notion"],
    repo: "marketdev/content-studio",
    installs: 1892,
    registered_at: "2026-01-08",
    version: "1.2.0",
    source: "community",
    verified: true,
    rating: 4.5,
    reviews_count: 217,
    stars: 1840,
    publisher: {
      name: "MarketDev Labs",
      handle: "marketdev",
      github_url: "https://github.com/marketdev",
      verified: true,
    },
    pricing: { kind: "free" },
  },
  {
    id: "mock-analytics-wizard",
    name: "Analytics Wizard",
    description:
      "Pull metrics from PostHog, Mixpanel, GA4. Builds weekly KPI digests, flags anomalies, drafts answers to investor questions.",
    category: "business",
    author: "data-team",
    tags: ["analytics", "metrics", "kpi", "posthog", "mixpanel"],
    icon_url: "chart-bar",
    integrations: ["posthog", "mixpanel", "googleanalytics", "slack", "notion"],
    repo: "data-team-oss/analytics-wizard",
    installs: 3401,
    registered_at: "2025-11-22",
    version: "2.4.3",
    source: "community",
    verified: true,
    rating: 4.8,
    reviews_count: 488,
    stars: 4210,
    publisher: {
      name: "Data Team OSS",
      handle: "data-team",
      github_url: "https://github.com/data-team-oss",
      verified: true,
    },
    pricing: {
      kind: "paid",
      price_cents: 1900,
      currency: "USD",
      model: "subscription",
    },
  },
  {
    id: "mock-invoice-hunter",
    name: "Invoice Hunter",
    description:
      "Chase unpaid invoices on a polite schedule. Writes follow-ups, flags risky accounts, tracks days outstanding. Never sends without approval.",
    category: "business",
    author: "saastools",
    tags: ["finance", "invoicing", "ar", "collections"],
    icon_url: "receipt",
    integrations: ["stripe", "quickbooks", "gmail", "outlook"],
    repo: "saastools/invoice-hunter",
    installs: 567,
    registered_at: "2026-02-19",
    version: "0.5.4",
    source: "community",
    verified: false,
    rating: 4.3,
    reviews_count: 73,
    stars: 421,
    publisher: {
      name: "SaaS Tools",
      handle: "saastools",
      github_url: "https://github.com/saastools",
      verified: false,
    },
    pricing: {
      kind: "paid",
      price_cents: 900,
      currency: "USD",
      model: "one_time",
    },
  },
  {
    id: "mock-meeting-scribe",
    name: "Meeting Scribe",
    description:
      "Joins your calls via Fireflies, writes structured notes, extracts action items, follows up the next day to make sure they happen.",
    category: "operations",
    author: "Ana López",
    tags: ["meetings", "notes", "fireflies", "productivity"],
    icon_url: "notebook",
    integrations: ["fireflies", "gong", "notion", "slack", "googlecalendar"],
    repo: "analopez/meeting-scribe",
    installs: 8234,
    registered_at: "2025-09-04",
    version: "3.1.2",
    source: "community",
    verified: true,
    rating: 4.9,
    reviews_count: 1124,
    stars: 9870,
    publisher: {
      name: "Ana López",
      handle: "analopez",
      github_url: "https://github.com/analopez",
      verified: true,
    },
    pricing: { kind: "free" },
  },
  {
    id: "mock-customer-insights",
    name: "Customer Insights",
    description:
      "Reads every support ticket, every Gong call, every churned account. Surfaces patterns weekly so product and CS stay ahead of churn.",
    category: "business",
    author: "growthhacker",
    tags: ["customer-success", "voc", "research", "gong"],
    icon_url: "magnifying-glass",
    integrations: ["gong", "intercom", "zendesk", "notion", "slack"],
    repo: "growthhacker/customer-insights",
    installs: 124,
    registered_at: "2026-04-30",
    version: "0.2.1",
    source: "community",
    verified: false,
    rating: 4.2,
    reviews_count: 18,
    stars: 87,
    publisher: {
      name: "Growth Hacker",
      handle: "growthhacker",
      github_url: "https://github.com/growthhacker",
      verified: false,
    },
    pricing: { kind: "free" },
  },
];
